import { LauncherConfig } from "@/types";

export const launchers: LauncherConfig[] = [
  {
    id: "fortress",
    name: "Fortress Shield",
    nameUr: "قلعہ شیلڈ",
    nameAr: "درع الحصن",
    icon: "🛡️",
    description: "Zero-Knowledge E2EE Security Hub",
    descUr: "زیرو نالج سیکیورٹی ہب",
    descAr: "مركز الأمان بدون معرفة",
    glassType: "emerald",
    accentColor: "#10b981",
    bgGradient: "linear-gradient(135deg, #ecfdf5 0%, #ffffff 50%, #d1fae5 100%)",
    features: ["AES-256-GCM Encryption", "WebAuthn Passkeys", "Zero-Trust mTLS", "FIPS 140-2 Level 3"],
    route: "/security",
  },
  {
    id: "crimson-vault",
    name: "Crimson Vault",
    nameUr: "کرمسن ویالٹ",
    nameAr: "خزنة القرمزي",
    icon: "🔐",
    description: "Encrypted Data Vault & Key Management",
    descUr: "انکرپٹڈ ڈیٹا والٹ",
    descAr: "خزنة البيانات المشفرة",
    glassType: "crimson",
    accentColor: "#f43f5e",
    bgGradient: "linear-gradient(135deg, #fff1f2 0%, #ffffff 50%, #ffe4e6 100%)",
    features: ["Key Rotation 30 Days", "Client-Side Decryption", "Secure Enclave", "Blind Storage"],
    route: "/vault",
  },
  {
    id: "nexus-sync",
    name: "Nexus Sync",
    nameUr: "نیکسس سنک",
    nameAr: "مزامنة نيكسوس",
    icon: "⚡",
    description: "Real-Time <50ms Encrypted Sync Engine",
    descUr: "ریئل ٹائم انکرپٹڈ سنک انجن",
    descAr: "محرك المزامنة المشفرة في الوقت الفعلي",
    glassType: "blue",
    accentColor: "#3b82f6",
    bgGradient: "linear-gradient(135deg, #eff6ff 0%, #ffffff 50%, #dbeafe 100%)",
    features: ["WebSocket gRPC", "<50ms Latency", "Blind Notifications", "IndexedDB Cache"],
    route: "/dashboard",
  },
  {
    id: "phantom-auth",
    name: "Phantom Auth",
    nameUr: "فینٹم آتھ",
    nameAr: "مصادقة الشبح",
    icon: "👁️",
    description: "Passwordless WebAuthn Biometric Auth",
    descUr: "بائیو میٹرک تصدیق سسٹم",
    descAr: "نظام مصادقة بيومترية",
    glassType: "purple",
    accentColor: "#8b5cf6",
    bgGradient: "linear-gradient(135deg, #f5f3ff 0%, #ffffff 50%, #ede9fe 100%)",
    features: ["FIDO2 Passkeys", "TOTP Fallback", "JWT 15-min", "Session Management"],
    route: "/webauthn",
  },
  {
    id: "oracle-monitor",
    name: "Oracle Monitor",
    nameUr: "اوریکل مانیٹر",
    nameAr: "مراقب أوراكل",
    icon: "📡",
    description: "Live Recharts Threat Intelligence Dashboards",
    descUr: "لائیو خطرات کا نظام",
    descAr: "استخبارات التهديدات المباشرة",
    glassType: "gold",
    accentColor: "#f59e0b",
    bgGradient: "linear-gradient(135deg, #fffbeb 0%, #ffffff 50%, #fef3c7 100%)",
    features: ["Live Recharts Graphs", "Threat Stream", "Latency Monitor", "Session Analytics"],
    route: "/dashboard",
  },
  {
    id: "domain-fortress",
    name: "Domain Fortress",
    nameUr: "ڈومین قلعہ",
    nameAr: "حصن النطاق",
    icon: "🏰",
    description: "Namecheap + Cloudflare DNS Control Center",
    descUr: "DNS سیکیورٹی کنٹرول سنٹر",
    descAr: "مركز التحكم في أمان DNS",
    glassType: "emerald",
    accentColor: "#059669",
    bgGradient: "linear-gradient(135deg, #ecfdf5 0%, #f0fdf4 50%, #dcfce7 100%)",
    features: ["DMARC p=reject", "CAA Records", "SSL Monitoring", "Auto-Renew"],
    route: "/domains",
  },
  {
    id: "email-hub",
    name: "Email Command Center",
    nameUr: "ای میل کمانڈ سنٹر",
    nameAr: "مركز قيادة البريد",
    icon: "📧",
    description: "Multi-account E2EE Email Management",
    descUr: "ملٹی اکاؤنٹ ای میل مینجمنٹ",
    descAr: "إدارة البريد الإلكتروني متعدد الحسابات",
    glassType: "blue",
    accentColor: "#3b82f6",
    bgGradient: "linear-gradient(135deg, #eff6ff 0%, #f0f9ff 50%, #dbeafe 100%)",
    features: ["Zoho + Gmail + Outlook", "Resend Integration", "E2EE Messages", "Multi-domain"],
    route: "/email",
  },
  {
    id: "website-hub",
    name: "Website Hub",
    nameUr: "ویب سائٹ ہب",
    nameAr: "مركز المواقع",
    icon: "🌐",
    description: "Netlify + Vercel + GitHub + Firebase Hosting",
    descUr: "ویب سائٹ ہوسٹنگ اور مینجمنٹ",
    descAr: "إدارة استضافة المواقع",
    glassType: "purple",
    accentColor: "#06b6d4",
    bgGradient: "linear-gradient(135deg, #ecfeff 0%, #f0fdff 50%, #cffafe 100%)",
    features: ["One-click Deploy", "GitHub CI/CD", "Multi-framework", "SSL Auto-renew"],
    route: "/websites",
  },
  {
    id: "integration-hub",
    name: "Integration Hub",
    nameUr: "انٹیگریشن ہب",
    nameAr: "مركز التكاملات",
    icon: "🔗",
    description: "12+ Provider Integrations — All in One Place",
    descUr: "تمام سروسز کا انضمام",
    descAr: "دمج جميع الخدمات في مكان واحد",
    glassType: "gold",
    accentColor: "#8b5cf6",
    bgGradient: "linear-gradient(135deg, #f5f3ff 0%, #faf5ff 50%, #ede9fe 100%)",
    features: ["Namecheap + Zoho", "Netlify + Cloudflare", "GitHub + Resend", "Supabase + Firebase"],
    route: "/integrations",
  },
];
